source 'https://rubygems.org'

group :development, :test do
  gem 'rake', '>= 12.3.3', :require => false
  gem 'rspec-puppet',            :require => false
  gem 'puppetlabs_spec_helper', '>= 0.4.1', :require => false
  gem 'rspec-system',            :require => false
  gem 'rspec-system-puppet',     :require => false
  gem 'rspec-system-serverspec', :require => false
end

if puppetversion = ENV['PUPPET_GEM_VERSION']
  gem 'puppet', puppetversion, :require => false
else
  gem 'puppet', :require => false
end
